set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR wasm32)

set(HWA_WASI_CLANG "" CACHE FILEPATH "Path to a clang with wasm32-wasi support")
set(HWA_WASI_SYSROOT "" CACHE PATH "Path to a WASI sysroot")
set(HWA_WASM_LD "" CACHE FILEPATH "Path to wasm-ld")
set(HWA_WASMTIME "" CACHE FILEPATH "Path to wasmtime")
set(HWA_WASM_TOOLS "" CACHE FILEPATH "Path to wasm-tools")
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES
  HWA_WASI_CLANG
  HWA_WASI_SYSROOT
  HWA_WASM_LD
  HWA_WASMTIME
  HWA_WASM_TOOLS)

if(NOT HWA_WASI_CLANG)
  find_program(HWA_WASI_CLANG NAMES clang REQUIRED)
endif()
if(NOT HWA_WASI_SYSROOT)
  message(FATAL_ERROR "Set HWA_WASI_SYSROOT to the WASI sysroot")
endif()
if(NOT HWA_WASM_LD)
  find_program(HWA_WASM_LD NAMES wasm-ld REQUIRED)
endif()
if(NOT HWA_WASMTIME)
  find_program(HWA_WASMTIME NAMES wasmtime REQUIRED)
endif()
if(NOT HWA_WASM_TOOLS)
  find_program(HWA_WASM_TOOLS NAMES wasm-tools REQUIRED)
endif()

set(CMAKE_C_COMPILER "${HWA_WASI_CLANG}")
set(CMAKE_C_COMPILER_TARGET wasm32-wasi)
set(CMAKE_SYSROOT "${HWA_WASI_SYSROOT}")
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_EXE_LINKER_FLAGS_INIT "-fuse-ld=${HWA_WASM_LD}")
set(CMAKE_CROSSCOMPILING_EMULATOR "${HWA_WASMTIME};run")

set(CMAKE_FIND_ROOT_PATH "${HWA_WASI_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
